on: [push, pull_request]
name: Code Inspection

jobs:
  inspect-code:
      name: Code Quality
      # if: github.event.pull_request.head.repo.full_name == github.repository
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v2
          with:
            ref: ${{ github.head_ref }}

        - name: black
          uses: lgeiger/black-action@v1.0.1
          with:
            args: .

        - name: Check for modified files
          id: git-check
          run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)

        - name: Push changes
          if: steps.git-check.outputs.modified == 'true'
          run: |
            git config --global user.name 'black formatter'
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
            git commit -am "Automated changes"
            git push
        - name: Analysing the code with pylint
          run: |
            python -m pip install pylint
            if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
            pylint $(git ls-files '*.py')